CREATE TABLE TBL_CLIENTE(
	CLI_ID INTEGER PRIMARY KEY,
	CLI_NOME VARCHAR(20) NOT NULL,
	CLI_SOBRENOME VARCHAR(20) NOT NULL,
	CLI_CPF NUMERIC(15) NOT NULL,
	CLI_RG NUMERIC(15) NOT NULL,
	CLI_EMAIL VARCHAR(50) NULL,
	CLI_ATIVO BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE SEQUENCE SEQ_CLI_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_CLIENTE
	ALTER COLUMN CLI_ID SET DEFAULT NEXTVAL('SEQ_CLI_ID'::REGCLASS);

CREATE TABLE TBL_TAG_RFID(
	TAG_ID INTEGER PRIMARY KEY,
	TAG_VALOR VARCHAR(20) NOT NULL,
	TAG_DESCRICAO VARCHAR(20) NULL,
	TAG_CLI_ID INTEGER REFERENCES TBL_CLIENTE(CLI_ID)
);

CREATE SEQUENCE SEQ_TAG_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_TAG_RFID
	ALTER COLUMN TAG_ID SET DEFAULT NEXTVAL('SEQ_TAG_ID'::REGCLASS);

CREATE TABLE TBL_ENDERECO(
	END_ID INTEGER PRIMARY KEY,
	END_LOGRADOURO VARCHAR(20) NOT NULL,
	END_CEP NUMERIC(15) NULL,
	END_NUMERO NUMERIC(10) NOT NULL,
	END_APTO NUMERIC(5) NULL,
	END_COMPLEMENTO VARCHAR(30) NULL,
	END_CLI_ID INTEGER REFERENCES TBL_CLIENTE(CLI_ID) NOT NULL
);

CREATE SEQUENCE SEQ_END_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_ENDERECO
	ALTER COLUMN END_ID SET DEFAULT NEXTVAL('SEQ_END_ID'::REGCLASS);

CREATE TABLE TBL_TELEFONES(
	TEL_ID INTEGER PRIMARY KEY,
	TEL_RESIDENCIAL VARCHAR(25) NOT NULL,
	TEL_CELULAR VARCHAR(25) NULL,
	TEL_CLI_ID INTEGER REFERENCES TBL_CLIENTE(CLI_ID) NOT NULL
);

CREATE SEQUENCE SEQ_TEL_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_TELEFONES
	ALTER COLUMN TEL_ID SET DEFAULT NEXTVAL('SEQ_TEL_ID'::REGCLASS);

CREATE TABLE TBL_CONTRATO(
	CONTR_ID INTEGER PRIMARY KEY,
	CONTR_DATA_INICIO DATE NOT NULL,
	CONTR_CLI_ID INTEGER REFERENCES TBL_CLIENTE(CLI_ID) NOT NULL
);

CREATE SEQUENCE SEQ_CONTR_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_CONTRATO
	ALTER COLUMN CONTR_ID SET DEFAULT NEXTVAL('SEQ_CONTR_ID'::REGCLASS);

CREATE TABLE TBL_FORMA_PAG(
	FORM_ID INTEGER PRIMARY KEY,
	FORM_DESCRICAO VARCHAR(20) NOT NULL UNIQUE
);

CREATE SEQUENCE SEQ_FORMA_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_FORMA_PAG
	ALTER COLUMN FORM_ID SET DEFAULT NEXTVAL('SEQ_FORMA_ID'::REGCLASS);

CREATE TABLE TBL_PAGAMENTOS(
	PAG_ID INTEGER PRIMARY KEY,
	PAG_VENCIMENTO DATE NOT NULL,
	PAG_PAGO BOOLEAN DEFAULT FALSE,
	PAG_CONTR_ID INTEGER REFERENCES TBL_CONTRATO(CONTR_ID),
	PAG_CLI_ID INTEGER REFERENCES TBL_CLIENTE(CLI_ID),
	PAG_FORM_ID INTEGER REFERENCES TBL_FORMA_PAG(FORM_ID)
);

CREATE SEQUENCE SEQ_PAG_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_PAGAMENTOS
	ALTER COLUMN PAG_ID SET DEFAULT NEXTVAL('SEQ_PAG_ID'::REGCLASS);

CREATE TABLE TBL_SERVICOS(
	SERV_ID INTEGER PRIMARY KEY,
	SERV_DESCRICAO VARCHAR(50) NOT NULL UNIQUE,
	SERV_VALOR NUMERIC(7, 2) NOT NULL
);

CREATE SEQUENCE SEQ_SERV_ID
	START WITH 1 
	INCREMENT BY 1 
	NO MINVALUE 
	NO MAXVALUE 
	CACHE 1;

ALTER TABLE TBL_SERVICOS
	ALTER COLUMN SERV_ID SET DEFAULT NEXTVAL('SEQ_SERV_ID'::REGCLASS);

CREATE TABLE TBL_CONTR_SERV(
	CV_CONTR_ID INTEGER REFERENCES TBL_CONTRATO(CONTR_ID),
	CV_SERV_ID INTEGER REFERENCES TBL_SERVICOS(SERV_ID),
	PRIMARY KEY(CV_CONTR_ID, CV_SERV_ID)
);

INSERT INTO TBL_FORMA_PAG (FORM_DESCRICAO) VALUES ('À Vista');
INSERT INTO TBL_FORMA_PAG (FORM_DESCRICAO) VALUES ('Cartão');

INSERT INTO TBL_SERVICOS (SERV_DESCRICAO, SERV_VALOR) VALUES ('Ginástica - Body Pump', to_number('60','99.99'));
INSERT INTO TBL_SERVICOS (SERV_DESCRICAO, SERV_VALOR) VALUES ('Capoeira', to_number('40.50','99.99'));
INSERT INTO TBL_SERVICOS (SERV_DESCRICAO, SERV_VALOR) VALUES ('Treinamento Funcional', to_number('90','99.99'));